set(ROGUE_ASSISTANT_VERSION_CORE 1.0.0)
set(ROGUE_ASSISTANT_VERSION_PRERELEASE beta.1)

if(NOT ROGUE_ASSISTANT_VERSION_CORE MATCHES "^[0-9]+[.][0-9]+[.][0-9]+$")
    message(FATAL_ERROR "ROGUE_ASSISTANT_VERSION_CORE must contain three numeric components")
endif()
if(NOT ROGUE_ASSISTANT_VERSION_PRERELEASE STREQUAL "" AND
   NOT ROGUE_ASSISTANT_VERSION_PRERELEASE MATCHES "^[0-9A-Za-z-]+([.][0-9A-Za-z-]+)*$")
    message(FATAL_ERROR "ROGUE_ASSISTANT_VERSION_PRERELEASE is invalid")
endif()

if(ROGUE_ASSISTANT_VERSION_PRERELEASE STREQUAL "")
    set(ROGUE_ASSISTANT_VERSION ${ROGUE_ASSISTANT_VERSION_CORE})
else()
    set(
        ROGUE_ASSISTANT_VERSION
        ${ROGUE_ASSISTANT_VERSION_CORE}-${ROGUE_ASSISTANT_VERSION_PRERELEASE}
    )
endif()
